//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multi.Tenant.Domain.OLTP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class OLTPContext : DbContext
    {
        public OLTPContext(string constring)
            : base(constring)
        {
        }
        public OLTPContext()
           : base()
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public virtual DbSet<User> Users { get; set; }
    }
}
