//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multi.Tenant.Domain.Config
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engagement
    {
        public int Id { get; set; }
        public string DBName { get; set; }
        public string EngagementDBServerName { get; set; }
        public string EngagementDBLogin { get; set; }
    }
}
